apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: judger-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete", "get", "list", "watch", "update"]
