---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hpcgame-judger
  namespace: hpcgame-judger-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpcgame-judger-binding
  namespace: hpcgame-judger-system
subjects:
  - kind: ServiceAccount
    name: hpcgame-judger
    namespace: hpcgame-judger-system
roleRef:
  kind: ClusterRole
  name: hpcgame-judger
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpcgame-judger
  namespace: hpcgame-judger-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hpcgame-judger
    control-plane: hpcgame-judger
  name: hpcgame-judger
  namespace: hpcgame-judger-system
spec:
  replicas: 3
  selector:
    matchLabels:
      control-plane: hpcgame-judger
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: hpcgame-judger
      labels:
        control-plane: hpcgame-judger
    spec:
      containers:
        - args:
            - -redis-config=redis://redis-replication.redis-system.svc:6379/14
            - -template-path=/templates
            - -rate-limit=128
          env:
            - name: RUNNER_ID
              valueFrom:
                secretKeyRef:
                  key: runner-id
                  name: runner-secret
            - name: RUNNER_KEY
              valueFrom:
                secretKeyRef:
                  key: runner-key
                  name: runner-secret
          command:
            - /manager
          image: crmirror.lcpu.dev/xtlsoft/hpcgame-judger:v0.1.0
          imagePullPolicy: Always
          name: hpcgame-judger
          resources:
            limits:
              cpu: "8"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: templates
              mountPath: /templates
      securityContext:
        runAsNonRoot: true
      serviceAccountName: hpcgame-judger
      terminationGracePeriodSeconds: 10
      volumes:
        - configMap:
            name: judger-templates
          name: templates
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: runner-secret
# type: Opaque
# stringData:
#   runner-id: <RUNNER_ID>
#   runner-key: <RUNNER_KEY>
